### ISSUE TITLE
Add left/right foot to bodyparts

### ISSUE THREAD

**Issue by denisov-vlad** [ML-KULeuven/socceraction#220]
In Perform's data we can split actions by left/right foot.

It is helpful when we know player's good foot. 

I've added it to `bodyparts` var 

```bodyparts: List[str] = ['foot', 'right foot', 'left foot', 'head', 'other', 'head/other']```

and `_get_bodypart_id()` function to increase xG classifier metrics. 

Is it ok? Will it break other functionality? I'm ready to make pull request.

**Comment by probberechts** [comment]
Yes, this will be a breaking change as people might filter data based on 'foot'. However, I agree that it would be useful to add this. Is Stats Perfom the only provider that distinguishes between the foot used? Otherwise, I would add this immediately for all providers that support it. 

This would require the following changes:

- You should add 'left foot' and 'right foot' add the end of the `bodyparts` list. Otherwise, it will break the mapping between IDs and names for data that was generated with a previous version of socceraction.
- Update [the `bodypart` and `bodypart_onehot` feature generators](https://github.com/ML-KULeuven/socceraction/blob/ed99f5d7bbaef3e610ac5a90612adb9ceba1a885/socceraction/vaep/features.py#L252) and map left/right foot both to 'foot' or 'better/worse foot'.

**Comment by denisov-vlad** [comment]
> Is Stats Perfom the only provider that distinguishes between the foot used?

I have only Stats Perform data and don't know about others.

> Update [the bodypart and bodypart_onehot feature generators](https://github.com/ML-KULeuven/socceraction/blob/ed99f5d7bbaef3e610ac5a90612adb9ceba1a885/socceraction/vaep/features.py#L252) and map left/right foot both to 'foot' or 'better/worse foot'.

Better/worse foot requires additional data from other Perform feeds. I've worked with MA3 and there is no info about preferred foot in events stream.
