### ISSUE TITLE
Opta parser fails to recognize headed passes

### ISSUE THREAD

**Issue by znstrider** [ML-KULeuven/socceraction#410]
Qualifier IDs:
3 Head pass: Pass made with a players head
168 Flick-on: Pass where a player has "flicked" the ball forward using their head
are not checked. Thus there aren't any headed passes.

I assume both should be added to _get_bodypart_id.

```python
def _get_bodypart_id(qualifiers: Dict[int, Any]) -> int:
    if 15 in qualifiers:
        b = 'head'
    elif 21 in qualifiers:
        b = 'other'
    else:
        b = 'foot'
    return spadlconfig.bodyparts.index(b)
```

should to be changed to:
```python
def _get_bodypart_id(qualifiers: Dict[int, Any]) -> int:
    if (15 in qualifiers) or (3 in qualifiers) or (168 in qualifiers):
        b = 'head'
    elif 21 in qualifiers:
        b = 'other'
    else:
        b = 'foot'
    return spadlconfig.bodyparts.index(b)
```

**Comment by probberechts** [comment]
You are right. It seems that qualifier `15` is poorly defined as "Any event where the player used their head such as a shot or a clearance". This definition suggests that all actions where the player used their head get the qualifier, but apparently passes are not included.

If you want you can create a pull request, otherwise I'll fix it later.
