### ISSUE TITLE
Some improvement suggestions: Brasileirão loading from Soccerdata, and adding substitutions in the events

### ISSUE THREAD

**Issue by Gibranium** [ML-KULeuven/socceraction#727]
It's only a list of improvements I'd like to see for the future since I use socceraction a lot. 
Maybe they're not really possible, or one can already use them but I don't know how to make them. 

• I'd like to see an event for substitutions to make possession adjusting metrics for players easier and more precise. 
• It would be great to enhance the loader so that it can load Brasileirão data acquired with soccerdata - I know it a problem related to special characters, but I don't know if it can be resolved.
• I know it's already in the "features", but it would be great to have a column - or more than one - for gamestate in the "events".
• I think it would be a great enhancement if the add_names functions for the atomic version could also add the results for the events. So - it's connected - last but not least, I'd really like to add the possibility to use the atomic vaep to build an xg model as in the notebooks for the non-atomic (maybe it's too much features to add to the atomic version, I don't really know). 

Thank you if you take time to read and answer me, even more if you'll implement something.

**Comment by probberechts** [comment]
> I'd like to see an event for substitutions to make possession adjusting metrics for players easier and more precise.

You can get the substitutions from the (provider)-specific events dataframe. We won't add them in the SPADL representation since they do not belong in it: substitutions are not actions.

> It would be great to enhance the loader so that it can load Brasileirão data acquired with soccerdata - I know it a problem related to special characters, but I don't know if it can be resolved.

Good point. Can you create a separate issue for this with a minimal code example illustrating the problem?

> I know it's already in the "features", but it would be great to have a column - or more than one - for gamestate in the "events".

Not sure whether you are referring to the provider-specific events or SPADL actions here. We won't do any post-processing on the events. That is out of scope. And I do not see the added value of adding game state by default to the SPADL actions. If you need this information, you can easily apply the corresponding feature transformers.

> I think it would be a great enhancement if the add_names functions for the atomic version could also add the results for the events.

The purpose of the atomic-SPADL format is essentially to remove the result from the actions. 

>  I'd really like to add the possibility to use the atomic vaep to build an xg model as in the notebooks for the non-atomic (maybe it's too much features to add to the atomic version, I don't really know).

SPADL is still the default format, unless Atomic-SPADL is a better fit for a certain application. For xG, Atomic-SPADL does not provide any benefits. We will not invest in maintaining alternative implementations if they do not offer added value.

**Comment by Gibranium** [comment]
> 
> Good point. Can you create a separate issue for this with a minimal code example illustrating the problem?
> 

Yes, no problem, I'll do it. Thanks for all the other answers and clarifications.
