### ISSUE TITLE
Questions about defensive events

### ISSUE THREAD

**Issue by madestro** [ML-KULeuven/socceraction#770]
Hello.  first of all great work.
My research group has been exploring several event-related football player scoring and we came to SPADL/VAEP some weeks ago.  I have some questions concerning the defensive events: 

1.- first of all why you leave aerial duels out of the analysis?.

2.- how do you encode "lost balls"? (when there is a duel that neither the attacker nor the defense obtain the ball, but a third player regain the possession)

3.- how do you encode if a player misses a defensive duel? I think it could be very interesting for evaluating the chances of conceding a goal for that action, even more if it is near their own area

Thanks!

**Comment by probberechts** [comment]
1. See #470. 
2. Ball recoveries are encoded as a "dribble" (i.e., carry) action.
3. Most providers have a "Challenge" (e.g., Opta) or "Dribbled Past" (e.g., StatsBomb) event to encode this. These events describe the player who gets dribbled past when a dribbler takes them on. It means that the player who gets dribbled past either did nothing at all or was not able to touch the ball. They do not have a counterpart in SPADL because they are not on-the-ball actions and do not change the game state (it provides exactly the same information as the dribble event). Therefore, they do not really fit into the framework.

**Comment by madestro** [comment]
Thanks! I forgot my last question that is: how do you encode a free kick which is, for instance, kicked at the right side of the field (from keeper's point of view) let's say at 20m from the goal line and the ball arrived at the same side near the another area, so the ball traveled around 60m,  it is not a short free kick and neither a crossed or shot free kick.

**Comment by probberechts** [comment]
The name `freekick_crossed` is not particulary well chosen and the definition in the docs is not entirely accurate. A better name would be `freekick_long`. Essentially, any freekick that is not a ground pass or a long ball is a `freekick_crossed`.
